let output;
output = document.all;
output = document.all[8];
output = document.all.length;
output = document.documentElement;
output = document.body.children;
output = document.doctype;
output = document.domain;
output = document.URL;
output = document.characterSet;
output = document.contentType;
output = document.forms;
output = document.forms[0].id;
output = document.forms[0].method;
output = document.forms[0].action;

// document.forms[0].id = 'newOne';
// output = document.links;
// output = document.links[0];
// output = document.links[0].href;
// output = document.links[0].id = 'lindile_link';
// output = document.links[0].href = 'weFarm.co.za';
// output = document.links[0].href = 'weFarm.co.za';
// output = document.links[0].className = 'My-Class';
// output = document.links[0].classList;
output = document.images;
output = document.images[0];
output = document.images[0].src;
console.log(output);
Array.from(document.forms).forEach((element) => {
  console.log(element);
});
